# -*- coding: utf-8 -*-
"""secure file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7KFJS4qx_-J55gPYnlaOQ2NkBs6SO9k
"""

from cryptography.fernet import Fernet
import base64
import ipywidgets as widgets
from IPython.display import display, FileLink

# Helper functions
def generate_key(password):
    return base64.urlsafe_b64encode(password.ljust(32).encode('utf-8'))

def encrypt_data(data, password):
    key = generate_key(password)
    fernet = Fernet(key)
    return fernet.encrypt(data)

def decrypt_data(data, password):
    key = generate_key(password)
    fernet = Fernet(key)
    return fernet.decrypt(data)

# Widgets
upload = widgets.FileUpload(accept='', multiple=False)
password = widgets.Password(description="Password:")
action = widgets.ToggleButtons(options=["Encrypt", "Decrypt"], description='Action:')
output = widgets.Output()

def process_file(b):
    with output:
        output.clear_output()
        if not upload.value:
            print("❗ Please upload a file.")
            return
        if not password.value:
            print("❗ Please enter a password.")
            return

        file_info = next(iter(upload.value.values()))
        content = file_info['content']
        filename = file_info['metadata']['name']

        try:
            if action.value == "Encrypt":
                result = encrypt_data(content, password.value)
                out_name = filename + ".enc"
                print(f"✅ Encrypted successfully! Saved as: {out_name}")
            else:
                result = decrypt_data(content, password.value)
                out_name = "decrypted_" + filename.replace(".enc", "")
                print(f"✅ Decrypted successfully! Saved as: {out_name}")

            with open(out_name, 'wb') as f:
                f.write(result)
            display(FileLink(out_name))

        except Exception as e:
            print("❌ Error:", str(e))

button = widgets.Button(description="Process File", button_style='success')
button.on_click(process_file)

display(upload, password, action, button, output)

