# -*- coding: utf-8 -*-
"""ssecure file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvf3T7pI56wTgtHe61-rwo1OV2daaIjm
"""



!pip install streamlit

import streamlit as st

from cryptography.fernet import Fernet
import base64
st.title("🔐 Secure File Vault")
st.write("Upload your file to encrypt or decrypt securely.")

# Generate a Fernet key from password
def generate_key(password):
    return base64.urlsafe_b64encode(password.ljust(32).encode('utf-8'))

# Encrypt file content
def encrypt_file(data, password):
    key = generate_key(password)
    fernet = Fernet(key)
    return fernet.encrypt(data)

# Decrypt file content
def decrypt_file(data, password):
    key = generate_key(password)
    fernet = Fernet(key)
    return fernet.decrypt(data)

# Upload section
action = st.selectbox("Choose Action", ["Encrypt a File", "Decrypt a File"])

password = st.text_input("Enter Password", type="password")
uploaded_file = st.file_uploader("Upload your file", type=None)

if uploaded_file and password:
    file_bytes = uploaded_file.read()

    if action == "Encrypt a File":
        encrypted_data = encrypt_file(file_bytes, password)
        st.success("✅ File Encrypted Successfully!")

        st.download_button(
            label="Download Encrypted File",
            data=encrypted_data,
            file_name=uploaded_file.name + ".enc"
        )

    elif action == "Decrypt a File":
        try:
            decrypted_data = decrypt_file(file_bytes, password)
            st.success("✅ File Decrypted Successfully!")

            st.download_button(
                label="Download Decrypted File",
                data=decrypted_data,
                file_name="decrypted_" + uploaded_file.name.replace(".enc", "")
            )

        except Exception as e:
            st.error("❌ Failed to decrypt. Wrong password or file corrupted.")





